
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/AppConfig'
export type * from './models/AccessToken'
export type * from './models/User'
export type * from './models/Group'
export type * from './models/Certificate'
export type * from './models/Notification'
export type * from './commonInputTypes'